services:
  consul:
    image: bitnami/consul:latest
    ports:
     - 8500:8500
    volumes:
     - ~/.docker-persistence/consul:/bitnami
  wialonips:
   image: gotrackery
   ports:
     - 5001:5001
   depends_on:
     - consul
   restart: on-failure:4
   environment:
     - GOTR_CONSUL=host.docker.internal:8500
     - GOTR_CONSUL_KEY=gotrackery/wialonips
   command:
     - tcp