name: Vet

on:
  push:
    branches:
      - '*'
#      - '!master'
  pull_request:
    branches: [main]

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - name: Run linters
        run: |
          make install-tools
          go vet ./...
          staticcheck ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: golangci-lint command line arguments.
          # args: --enable-all

            # Optional: show only new issues if it's a pull request. The default value is `false`.
            # only-new-issues: true

            # Optional: if set to true then the all caching functionality will be complete disabled,
            #           takes precedence over all other caching options.
            # skip-cache: true

            # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

      - name: Run tests
        run: make tests